version: '3.8'
services:
  postgres-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

volumes:
  postgres_data:
networks:
  django_network:
